# ---------------------------------------------------------------------------
# HomeBrew Repeater Protocol constants used by ipsc2hbp.
# ---------------------------------------------------------------------------

HBPF_DMRD = b"DMRD"
HBPF_RPTL = b"RPTL"
HBPF_RPTK = b"RPTK"
HBPF_RPTC = b"RPTC"
HBPF_RPTACK = b"RPTACK"
HBPF_MSTNAK = b"MSTNAK"
HBPF_RPTPING = b"RPTPING"
HBPF_MSTPONG = b"MSTPONG"
HBPF_RPTO = b"RPTO"
HBPF_RPTCL = b"RPTCL"
HBPF_MSTCL = b"MSTCL"

HBPF_CMD_DMRD = b"DMRD"
HBPF_CMD_RPTA = b"RPTA"
HBPF_CMD_MSTN = b"MSTN"
HBPF_CMD_MSTP = b"MSTP"
HBPF_CMD_MSTC = b"MSTC"
HBPF_CMD_RPTP = b"RPTP"

HBPF_TGID_TS2 = 0x80
HBPF_TGID_CALL_P = 0x40
HBPF_FRAMETYPE_VOICE = 0x00
HBPF_FRAMETYPE_VOICESYNC = 0x10
HBPF_FRAMETYPE_DATASYNC = 0x20
HBPF_SLT_VHEAD = 0x01
HBPF_SLT_VTERM = 0x02
HBPF_FRAMETYPE_MASK = 0x30
HBPF_DTYPE_MASK = 0x0F

DMRD_LEN = 55
DMRD_MAGIC_OFF = 0
DMRD_SEQ_OFF = 4
DMRD_SRC_OFF = 5
DMRD_DST_OFF = 8
DMRD_RPTR_OFF = 11
DMRD_FLAGS_OFF = 15
DMRD_STREAM_OFF = 16
DMRD_PAYLOAD_OFF = 20
DMRD_BER_OFF = 53
DMRD_RSSI_OFF = 54

RPTC_LEN = 302
RPTC_RADIO_ID = slice(4, 8)
RPTC_CALLSIGN = slice(8, 16)
RPTC_RX_FREQ = slice(16, 25)
RPTC_TX_FREQ = slice(25, 34)
RPTC_TX_POWER = slice(34, 36)
RPTC_COLORCODE = slice(36, 38)
RPTC_LATITUDE = slice(38, 46)
RPTC_LONGITUDE = slice(46, 55)
RPTC_HEIGHT = slice(55, 58)
RPTC_LOCATION = slice(58, 78)
RPTC_DESCRIPTION = slice(78, 97)
RPTC_SLOTS = slice(97, 98)
RPTC_URL = slice(98, 222)
RPTC_SOFTWARE_ID = slice(222, 262)
RPTC_PACKAGE_ID = slice(262, 302)
RPTC_SLOTS_VALUE = b"3"

RPTACK_NONCE_OFF = 6
RPTACK_ID_OFF = 6
MSTPONG_ID_OFF = 7
MSTCL_ID_OFF = 5
